name: huluxia_signin
on:
  # 每天 18:00 UTC 时间触发（对应北京时间 2:00）
  schedule:
    - cron: '00 18 * * *'
  # 手动触发选项
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Script
        id: signin-outputs
        env:
          NOTIFIER_TYPE:  $ {{ secrets NOTIFIER_TYPE }}
          EMAIL_CONFIG:  $ {{ secrets.EMAIL_CONFIG }}
          # WECHAT_ROBOT_URL:  $ {{ secrets.WECHAT ROBOT_URL }}
          ACCOUNTS:  $ {{ secrets.ACCOUNTS }}
        run: |      
          python ./main.py
